# -*- coding: utf-8 -*-
"""이메일 작성 자동화.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzLhtd6uaOiNuZ90OJD4SOb4S_6fz2d8
"""

from openai import OpenAI

# API 키 설정
from google.colab import userdata
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')

client = OpenAI(api_key=OPENAI_API_KEY)

# 1. 샘플 데이터
data = """
행사명: 2025년 연구 성과 발표회
일시: 2025년 9월 10일 오후 2시
장소: ○○연구원 국제회의실
목적: 연구 성과 공유 및 산학 협력 강화
요청사항: 각 부서별 1명 이상 참석, 발표자료 9월 5일까지 제출
"""

# 2. 프롬프트 생성
prompt = f"""
너는 행정 공문 작성 전문가야.
다음 데이터를 바탕으로 공식적인 공문을 작성해줘.

데이터:
{data}

형식:
- 문서 제목
- 수신자
- 발신자
- 본문 (배경, 요청/안내 사항, 협조 요청)
- 결재란

톤: 격식 있고 간결한 공문 스타일
"""

# 3. LLM 호출
response = client.chat.completions.create(
    model="gpt-4o-mini",   # 필요시 "gpt-4o" 또는 "gpt-4.1" 등으로 교체 가능
    messages=[
        {"role": "system", "content": "You are a professional administrative document writer."},
        {"role": "user", "content": prompt}
    ],
    temperature=0.3
)

# 4. 결과 출력

from IPython.display import Markdown
Markdown(response.choices[0].message.content)